package com.singhDevs.chezz

import com.singhDevs.chezz.websocket.MessageActions
import com.singhDevs.chezz.websocket.WebSocketClient
import com.github.bhlangonijr.chesslib.Square

object Constants {
    lateinit var webSocketClient: WebSocketClient
    val squareMapping = mutableMapOf(
        "a1" to Square.A1,
        "a2" to Square.A2,
        "a3" to Square.A3,
        "a4" to Square.A4,
        "a5" to Square.A5,
        "a6" to Square.A6,
        "a7" to Square.A7,
        "a8" to Square.A8,
        "b1" to Square.B1,
        "b2" to Square.B2,
        "b3" to Square.B3,
        "b4" to Square.B4,
        "b5" to Square.B5,
        "b6" to Square.B6,
        "b7" to Square.B7,
        "b8" to Square.B8,
        "c1" to Square.C1,
        "c2" to Square.C2,
        "c3" to Square.C3,
        "c4" to Square.C4,
        "c5" to Square.C5,
        "c6" to Square.C6,
        "c7" to Square.C7,
        "c8" to Square.C8,
        "d1" to Square.D1,
        "d2" to Square.D2,
        "d3" to Square.D3,
        "d4" to Square.D4,
        "d5" to Square.D5,
        "d6" to Square.D6,
        "d7" to Square.D7,
        "d8" to Square.D8,
        "e1" to Square.E1,
        "e2" to Square.E2,
        "e3" to Square.E3,
        "e4" to Square.E4,
        "e5" to Square.E5,
        "e6" to Square.E6,
        "e7" to Square.E7,
        "e8" to Square.E8,
        "f1" to Square.F1,
        "f2" to Square.F2,
        "f3" to Square.F3,
        "f4" to Square.F4,
        "f5" to Square.F5,
        "f6" to Square.F6,
        "f7" to Square.F7,
        "f8" to Square.F8,
        "g1" to Square.G1,
        "g2" to Square.G2,
        "g3" to Square.G3,
        "g4" to Square.G4,
        "g5" to Square.G5,
        "g6" to Square.G6,
        "g7" to Square.G7,
        "g8" to Square.G8,
        "h1" to Square.H1,
        "h2" to Square.H2,
        "h3" to Square.H3,
        "h4" to Square.H4,
        "h5" to Square.H5,
        "h6" to Square.H6,
        "h7" to Square.H7,
        "h8" to Square.H8
    )
    val squareToCharMapping = mutableMapOf(
        Square.A1 to "a1",
        Square.A2 to "a2",
        Square.A3 to "a3",
        Square.A4 to "a4",
        Square.A5 to "a5",
        Square.A6 to "a6",
        Square.A7 to "a7",
        Square.A8 to "a8",
        Square.B1 to "b1",
        Square.B2 to "b2",
        Square.B3 to "b3",
        Square.B4 to "b4",
        Square.B5 to "b5",
        Square.B6 to "b6",
        Square.B7 to "b7",
        Square.B8 to "b8",
        Square.C1 to "c1",
        Square.C2 to "c2",
        Square.C3 to "c3",
        Square.C4 to "c4",
        Square.C5 to "c5",
        Square.C6 to "c6",
        Square.C7 to "c7",
        Square.C8 to "c8",
        Square.D1 to "d1",
        Square.D2 to "d2",
        Square.D3 to "d3",
        Square.D4 to "d4",
        Square.D5 to "d5",
        Square.D6 to "d6",
        Square.D7 to "d7",
        Square.D8 to "d8",
        Square.E1 to "e1",
        Square.E2 to "e2",
        Square.E3 to "e3",
        Square.E4 to "e4",
        Square.E5 to "e5",
        Square.E6 to "e6",
        Square.E7 to "e7",
        Square.E8 to "e8",
        Square.F1 to "f1",
        Square.F2 to "f2",
        Square.F3 to "f3",
        Square.F4 to "f4",
        Square.F5 to "f5",
        Square.F6 to "f6",
        Square.F7 to "f7",
        Square.F8 to "f8",
        Square.G1 to "g1",
        Square.G2 to "g2",
        Square.G3 to "g3",
        Square.G4 to "g4",
        Square.G5 to "g5",
        Square.G6 to "g6",
        Square.G7 to "g7",
        Square.G8 to "g8",
        Square.H1 to "h1",
        Square.H2 to "h2",
        Square.H3 to "h3",
        Square.H4 to "h4",
        Square.H5 to "h5",
        Square.H6 to "h6",
        Square.H7 to "h7",
        Square.H8 to "h8"
    )
    val alphabets = "abcdefghijklmnopqrstuvwxyz"

    fun initClient(messageActions: MessageActions){
        this.webSocketClient = WebSocketClient(messageActions)
    }
}