package com.singhDevs.chezz.models.chessboard

data class Board(
    val _board: List<Square?> = DEFAULT_BOARD,
    val _castling: Castling = Castling(0, 0),
    val _comments: Comments = Comments(),
    val _epSquare: Int = 0,
    val _halfMoves: Int = 0,
    val _header: Header = Header(),
    val _history: List<History> = emptyList(),
    val _kings: Kings = Kings(0, 0),
    val _moveNumber: Int = 0,
    val _positionCount: PositionCount = PositionCount(0, 0),
    val _turn: String = "w"
) {
    companion object{
        val DEFAULT_BOARD = listOf(
            Square("b", "r"),
            Square("b", "n"),
            Square("b", "b"),
            Square("b", "q"),
            Square("b", "k"),
            Square("b", "b"),
            Square("b", "n"),
            Square("b", "r"),
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            Square("b", "p"),
            Square("b", "p"),
            Square("b", "p"),
            Square("b", "p"),
            Square("b", "p"),
            Square("b", "p"),
            Square("b", "p"),
            Square("b", "p"),
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            Square("w", "p"),
            Square("w", "p"),
            Square("w", "p"),
            Square("w", "p"),
            Square("w", "p"),
            Square("w", "p"),
            Square("w", "p"),
            Square("w", "p"),
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            Square("w", "r"),
            Square("w", "n"),
            Square("w", "b"),
            Square("w", "q"),
            Square("w", "k"),
            Square("w", "b"),
            Square("w", "n"),
            Square("w", "r"),
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
        )
    }
}